swagger: '2.0'
info:
  title: Wine Category Recommendation by Description API
  version: "0.1"
  description: An API that when given tasting notes and food pairing will return a category of wine that best aligns with that description. 

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: wine_category_api.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /predict:
    post:
      summary: Entrypoint to our prediction function
      operationId: wine_category_api.predict
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: wine_description
          required: true
          description: Description of tasting notes or food you wish to pair with wine
          type: string
      responses:
        '200':
          description: Classification performed successfully
        '500':
          description: Unable to perform the classification